export { TableSkeleton } from "./table-skeleton";
export { AdminDashboardSkeleton } from "./admin-dashboard-skeleton";
export { AccountLayoutSkeleton } from "./account-layout-skeleton";
export { OrderDetailSkeleton } from "./order-detail-skeleton";
export { ProductDetailSkeleton } from "./product-detail-skeleton";
export { OrderListSkeleton } from "./order-list-skeleton";
export { CatalogSkeleton } from "./catalog-skeleton";
export { CheckoutSkeleton } from "./checkout-skeleton";
export { CartSkeleton } from "./cart-skeleton";
